# Generated by Django 4.2.21 on 2025-06-16 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="생성된 시험", max_length=255, verbose_name="시험 제목"
                    ),
                ),
                (
                    "num_questions_requested",
                    models.PositiveIntegerField(
                        default=10, verbose_name="요청 문제 수"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요 표시"),
                ),
            ],
            options={
                "verbose_name": "시험 세트",
                "verbose_name_plural": "시험 세트 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserTestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작 시간"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="점수"),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요 오답노트"),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="응시 시간(초)"
                    ),
                ),
                (
                    "test_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="flo_my.testset",
                        verbose_name="응시 시험",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="응시자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 시험 응시 기록",
                "verbose_name_plural": "사용자 시험 응시 기록 목록",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="pdfs/%Y/%m/%d/", verbose_name="PDF 파일"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="원본 파일명"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "업로드된 PDF",
                "verbose_name_plural": "업로드된 PDF 목록",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="testset",
            name="source_pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flo_my.uploadedpdf",
                verbose_name="원본 PDF",
            ),
        ),
        migrations.AddField(
            model_name="testset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="문제 내용")),
                (
                    "explanation",
                    models.TextField(blank=True, null=True, verbose_name="해설"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="문제 순서"),
                ),
                (
                    "test_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="flo_my.testset",
                        verbose_name="시험 세트",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 문제",
                "verbose_name_plural": "시험 문제 목록",
                "ordering": ["test_set", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="학습 목표 제목"),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("TEST_RETAKE", "Test 전체 다시 풀기"),
                            ("INCORRECT_ANSWERS_RETAKE", "오답만 다시 풀기"),
                        ],
                        max_length=30,
                        verbose_name="목표 유형",
                    ),
                ),
                (
                    "target_repetition_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="목표 반복 학습 횟수"
                    ),
                ),
                (
                    "current_repetition_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="현재 완료 횟수"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="학습 마감일")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="중요 목표 여부"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="목표 달성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "target_attempt_for_incorrect_notes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals_for_incorrect_retake",
                        to="flo_my.usertestattempt",
                        verbose_name="오답노트 대상 응시기록",
                    ),
                ),
                (
                    "target_test_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals_for_test_retake",
                        to="flo_my.testset",
                        verbose_name="대상 TestSet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학습 목표",
                "verbose_name_plural": "학습 목표 목록",
                "ordering": ["-is_important", "due_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="보기 내용")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="정답 여부"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="flo_my.question",
                        verbose_name="관련 문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "객관식 보기",
                "verbose_name_plural": "객관식 보기 목록",
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="정답 여부"
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="flo_my.usertestattempt",
                        verbose_name="응시 기록",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flo_my.question",
                        verbose_name="질문",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flo_my.choice",
                        verbose_name="선택한 보기",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 답변",
                "verbose_name_plural": "사용자 답변 목록",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
