# Generated by Django 4.2.21 on 2025-06-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flo_exam", "0003_userexamsession_is_important"),
        ("flo_my", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learninggoal",
            name="target_attempt_for_incorrect_notes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_goals_for_incorrect_retake",
                to="flo_exam.userexamsession",
                verbose_name="오답노트 대상 응시기록",
            ),
        ),
        migrations.AlterField(
            model_name="learninggoal",
            name="target_test_set",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="learning_goals_for_test_retake",
                to="flo_exam.examdocument",
                verbose_name="대상 시험 (전체 다시 풀기)",
            ),
        ),
    ]
