# Generated by Django 4.2.21 on 2025-06-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "flo_my",
            "0002_alter_learninggoal_target_attempt_for_incorrect_notes_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="test_set",
        ),
        migrations.RemoveField(
            model_name="testset",
            name="source_pdf",
        ),
        migrations.RemoveField(
            model_name="testset",
            name="user",
        ),
        migrations.RemoveField(
            model_name="uploadedpdf",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="attempt",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="useranswer",
            name="selected_choice",
        ),
        migrations.RemoveField(
            model_name="usertestattempt",
            name="test_set",
        ),
        migrations.RemoveField(
            model_name="usertestattempt",
            name="user",
        ),
        migrations.AlterField(
            model_name="learninggoal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("TEST_RETAKE", "시험 다시 풀기"),
                    ("INCORRECT_ANSWERS_RETAKE", "오답만 다시 풀기"),
                ],
                max_length=30,
                verbose_name="목표 유형",
            ),
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
        migrations.DeleteModel(
            name="TestSet",
        ),
        migrations.DeleteModel(
            name="UploadedPDF",
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
        migrations.DeleteModel(
            name="UserTestAttempt",
        ),
    ]
