# Generated by Django 4.2.21 on 2025-06-16 12:36

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4, "아이디는 4자 이상이어야 합니다."
                            ),
                            django.core.validators.RegexValidator(
                                code="invalid_username",
                                message="아이디는 영문자와 숫자만 사용할 수 있습니다.",
                                regex="^[a-zA-Z0-9]+$",
                            ),
                        ],
                        verbose_name="아이디",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "닉네임은 2자 이상이어야 합니다."
                            ),
                            django.core.validators.RegexValidator(
                                code="invalid_nickname",
                                message="닉네임은 한글, 영문자, 숫자만 사용할 수 있습니다.",
                                regex="^[가-힣a-zA-Z0-9]+$",
                            ),
                        ],
                        verbose_name="닉네임",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                2, "이름은 2자 이상이어야 합니다."
                            ),
                            django.core.validators.RegexValidator(
                                code="invalid_name",
                                message="이름은 한글과 영문자만 사용할 수 있습니다.",
                                regex="^[가-힣a-zA-Z]+$",
                            ),
                        ],
                        verbose_name="이름",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="이메일"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to.",
                        related_name="custom_user_set",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="InterestTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserTermAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agree_age_confirm", models.BooleanField()),
                ("agree_service", models.BooleanField()),
                ("agree_privacy", models.BooleanField()),
                ("agree_ai_data", models.BooleanField()),
                ("agree_marketing", models.BooleanField(default=False)),
                ("agree_outsourcing", models.BooleanField()),
                ("agreed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_bio", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "남성"),
                            ("female", "여성"),
                            ("other", "기타"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("student", "학생"),
                            ("developer", "개발자"),
                            ("designer", "디자이너"),
                            ("pm", "기획자"),
                            ("etc", "기타"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                ("activity_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                (
                    "interests",
                    models.ManyToManyField(blank=True, to="accounts.interesttag"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
