# Generated by Django 4.2.21 on 2025-06-04 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2, '이름은 2자 이상이어야 합니다.'), django.core.validators.RegexValidator(code='invalid_name', message='이름은 한글과 영문자만 사용할 수 있습니다.', regex='^[가-힣a-zA-Z]+$')], verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(2, '닉네임은 2자 이상이어야 합니다.'), django.core.validators.RegexValidator(code='invalid_nickname', message='닉네임은 한글, 영문자, 숫자만 사용할 수 있습니다.', regex='^[가-힣a-zA-Z0-9]+$')], verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4, '아이디는 4자 이상이어야 합니다.'), django.core.validators.RegexValidator(code='invalid_username', message='아이디는 영문자와 숫자만 사용할 수 있습니다.', regex='^[a-zA-Z0-9]+$')], verbose_name='아이디'),
        ),
    ]
