# Generated by Django 4.2.21 on 2025-06-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_alter_user_name_alter_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='UserTermAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree_age_confirm', models.BooleanField()),
                ('agree_service', models.BooleanField()),
                ('agree_privacy', models.BooleanField()),
                ('agree_ai_data', models.BooleanField()),
                ('agree_marketing', models.BooleanField(default=False)),
                ('agree_outsourcing', models.BooleanField()),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
