
"""
Django settings for flo_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv # python-dotenv 임포트

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일의 위치를 정확히 지정해야 합니다.
# 일반적으로 .env 파일은 manage.py 파일과 같은 프로젝트 루트 디렉토리에 위치합니다.
# BASE_DIR은 현재 settings.py 파일이 있는 디렉토리의 부모 디렉토리(프로젝트 루트)를 가리킵니다.
ENV_PATH = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path=ENV_PATH) # .env 파일 로드 명시적 경로 지정


AUTH_USER_MODEL = 'accounts.User'  # accounts 앱의 User 모델 사용

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = 'django-insecure-6^t_%3mawcn$k-mglzc#509$uo=wzpjb*cctv0sbmk-9*o)&(='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',  # 추가한 부분
    'tinymce',  # 추가된 부분
    'flo.apps.FloConfig',  # 추가된 부분
    'accounts.apps.AccountsConfig',  # accounts 앱 추가
    'flo_exam.apps.FloExamConfig' # 추가된 부분 / flo프로그램 페이지
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',  # 다국어 지원을 위한 미들웨어 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            os.path.join(BASE_DIR, 'flo_project', 'templates'),
            os.path.join(BASE_DIR, 'flo', 'templates'),
            os.path.join(BASE_DIR, 'accounts', 'templates'),
            os.path.join(BASE_DIR, 'flo_exam', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # 추가된 부분 (이미지 안 뜨면 이 부분 보기)
            ],
        },
    },
]

WSGI_APPLICATION = 'flo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # === 아래 'OPTIONS' 블록을 추가해주세요 ===
        'OPTIONS': {
            'timeout': 20,  # 기본값 5초에서 20초로 늘립니다.
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko'

LANGUAGES = [
    ('en', 'English'),
    ('ko', 'Korean'),
    ('es', 'Spanish'),
]

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR / 'locale'),
]


TIME_ZONE = 'Asia/Seoul'
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [

    os.path.join(BASE_DIR, 'static'),
]  # 추가된 부분

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Vectorstore Root
VECTORSTORE_ROOT = os.path.join(BASE_DIR, 'vectorstores')
if not os.path.exists(VECTORSTORE_ROOT):
    os.makedirs(VECTORSTORE_ROOT)
if not os.path.exists(os.path.join(VECTORSTORE_ROOT, 'document_specific_vs')):
    os.makedirs(os.path.join(VECTORSTORE_ROOT, 'document_specific_vs'))

# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'purpleluna56756@gmail.com'
# EMAIL_HOST_PASSWORD = 'alde sjpl ftrq xiqx'
# DEFAULT_FROM_EMAIL = 'webmaster@localhost'

#테스트용 시우계정 이메일
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'thfdl136@gmail.com'
EMAIL_HOST_PASSWORD = 'bmlkucwuntnivhlf' 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# OpenAI API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    print("경고: .env 파일에서 OPENAI_API_KEY를 로드하지 못했습니다. settings.py와 .env 파일 설정을 확인하세요.")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 로그인 성공 후 리디렉션될 URL (예: 홈페이지 또는 게시판 목록)
LOGIN_REDIRECT_URL = 'flo:home' # 또는 '/' 등 원하는 경로

# 로그인이 필요한 페이지 접근 시 리디렉션될 URL (login 뷰의 name)
LOGIN_URL = 'flo:login'

# 로그아웃 성공 후 리디렉션될 URL

LOGOUT_REDIRECT_URL = 'flo:home' # 또는 '/' 등 원하는 경로

# settings.py
# 이메일 보내기 설정 (개발용)
# 실제 이메일로 인증하고 싶으면 아래 2줄을 지우면 됨.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    # EmailBackend: 이메일에서 보낸 것처럼 링크를 보여줌.
        # <a href="http://127.0.0.1:8000/accounts/activate/MTE/comdnf-50575b9549f83384b77e42c119d7709d/">http://127.0.0.1:8000/accounts/activate/MTE/comdnf-50575b9549f83384b77e42c119d7709d/</a>
            # 위 링크에서 http://127.0.0.1:8000/accounts/activate/MTE/comdnf-50575b9549f83384b77e42c119d7709d/를 들어가면 마치 이메일 인증을 받은 것 같은 효과를 줌.
DEFAULT_FROM_EMAIL = 'webmaster@localhost'


    
# 1. .env에서 TinyMCE API 키를 불러옵니다.
TINYMCE_API_KEY = os.environ.get("TINYMCE_API_KEY")

if not TINYMCE_API_KEY:
    # 키가 없는 경우 기본 'no-api-key'를 사용하거나 오류를 발생시킬 수 있습니다.
    # 'no-api-key'를 사용하면 개발자 모드로 작동하며, 도메인 등록 알림이 계속 뜹니다.
    TINYMCE_API_KEY = 'no-api-key' 
    print("경고: .env 파일에서 TINYMCE_API_KEY를 찾을 수 없습니다. 개발자 모드로 실행됩니다.")

# 2. 불러온 키를 사용하여 TINYMCE_JS_URL을 동적으로 설정합니다.
TINYMCE_JS_URL = f"https://cdn.tiny.cloud/1/xqn37s38iyj7twa9wlozw51dfmv2mqxbxsr6le9amrbajhlc/tinymce/7/tinymce.min.js"

TINYMCE_DEFAULT_CONFIG = {
    'height': 360,
    'menubar': False, # Based on your image
    'plugins': 'advlist autolink lists link image charmap preview anchor '
               'searchreplace visualblocks code fullscreen insertdatetime media table '
               'help wordcount', # Common plugins, adjust as needed
    'toolbar': 'undo redo | formatselect | fontsizeselect | ' # Added font size
               'bold italic underline strikethrough | '
               'link image media table | ' # Added table
               'alignleft aligncenter alignright alignjustify | '
               'bullist numlist outdent indent | '
               'removeformat | code | help',
    'content_style': "body { background-color: #FFFFFF; color: #333333; font-family: Pretendard-Regular; } " +
                     "body.mce-content-body::placeholder { color: #a0a0a0; opacity: 1; }",
    # Add other default settings if needed
}
TINYMCE_SPELLCHECKER = False

TINYMCE_COMPRESSOR = False # Usually not needed with minified CDN versions

THEME_MODE = 'light' #맥에서는 안깨지는데 윈도우에서 자꾸 이미지때문에 깨지는 이유로 하드코딩딩
