"""
Django settings for flo_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv # python-dotenv 임포트

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일의 위치를 정확히 지정해야 합니다.
# 일반적으로 .env 파일은 manage.py 파일과 같은 프로젝트 루트 디렉토리에 위치합니다.
# BASE_DIR은 현재 settings.py 파일이 있는 디렉토리의 부모 디렉토리(프로젝트 루트)를 가리킵니다.
ENV_PATH = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path=ENV_PATH) # .env 파일 로드 명시적 경로 지정

AUTH_USER_MODEL = 'accounts.User'  # accounts 앱의 User 모델 사용

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-88+8)+%86)(@u#@xmx-gh8v+b!=j3@4ivsiqwqr&8yt*3m9g@t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modeltranslation',  # 추가한 부분
    'tinymce',  # 추가된 부분
    'flo.apps.FloConfig',  # 추가된 부분
    'accounts',  # accounts 앱 추가
]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',  # 다국어 지원을 위한 미들웨어 추가
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flo_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            os.path.join(BASE_DIR, 'flo', 'templates'),
            os.path.join(BASE_DIR, 'accounts', 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'flo_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko'

LANGUAGES = [
    ('en', 'English'),
    ('ko', 'Korean'),
    ('es', 'Spanish'),
]

USE_I18N = True
USE_L10N = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR / 'locale'),
]

TIME_ZONE = 'Asia/Seoul'
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Vectorstore Root
VECTORSTORE_ROOT = os.path.join(BASE_DIR, 'vectorstores')
if not os.path.exists(VECTORSTORE_ROOT):
    os.makedirs(VECTORSTORE_ROOT)
if not os.path.exists(os.path.join(VECTORSTORE_ROOT, 'document_specific_vs')):
    os.makedirs(os.path.join(VECTORSTORE_ROOT, 'document_specific_vs'))

# Email settings
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'purpleluna56756@gmail.com'
# EMAIL_HOST_PASSWORD = 'alde sjpl ftrq xiqx'
# DEFAULT_FROM_EMAIL = 'webmaster@localhost'

#테스트용 시우계정 이메일
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'thfdl136@gmail.com'
EMAIL_HOST_PASSWORD = 'bmlkucwuntnivhlf' 
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Login/Logout URLs
LOGIN_REDIRECT_URL = 'flo:study_post_list'
LOGIN_URL = 'flo:login'
LOGOUT_REDIRECT_URL = 'flo:study_post_list'

# OpenAI API Key
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
if not OPENAI_API_KEY:
    print("경고: .env 파일에서 OPENAI_API_KEY를 로드하지 못했습니다. settings.py와 .env 파일 설정을 확인하세요.")

# TinyMCE settings
TINYMCE_DEFAULT_CONFIG = {
    "height": "350px",
    "width": "100%",
    "menubar": "file edit view insert format tools table help",
    "plugins": (
        "advlist autolink lists link image charmap print preview anchor "
        "searchreplace visualblocks code fullscreen insertdatetime media table "
        "paste code help wordcount"
    ),
    "toolbar": (
        "undo redo | styleselect | bold italic underline strikethrough | "
        "alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | link image media | "
        "forecolor backcolor | removeformat | code fullscreen | help"
    ),
    "custom_undo_redo_levels": 10,
    "branding": False,
    "statusbar": True,
    "content_style": (
        "body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif; "
        "font-size: 14px; color: #212529; background-color: #ffffff; line-height: 1.6; margin: 10px; } "
        "p { margin: 0 0 10px 0; } "
        "img { max-width: 100%; height: auto; }"
    ),
    "placeholder": "내용을 입력하세요.",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


THEME_MODE = 'light' #맥에서는 안깨지는데 윈도우에서 자꾸 이미지때문에 깨지는 이유로 하드코딩딩