# Generated by Django 5.2.1 on 2025-06-02 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='FAQ 카테고리명')),
            ],
            options={
                'verbose_name': 'FAQ 카테고리',
                'verbose_name_plural': 'FAQ 카테고리 목록',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='카테고리명')),
                ('slug', models.SlugField(allow_unicode=True, help_text='URL에 사용될 이름', unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='flo.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '전체 카테고리',
                'verbose_name_plural': '전체 카테고리 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MajorCategory',
            fields=[
            ],
            options={
                'verbose_name': '학습 게시판 대분류',
                'verbose_name_plural': '학습 게시판 대분류',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flo.category',),
        ),
        migrations.CreateModel(
            name='MediumCategory',
            fields=[
            ],
            options={
                'verbose_name': '학습 게시판 중분류',
                'verbose_name_plural': '학습 게시판 중분류',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flo.category',),
        ),
        migrations.CreateModel(
            name='MinorCategory',
            fields=[
            ],
            options={
                'verbose_name': '학습 게시판 소분류',
                'verbose_name_plural': '학습 게시판 소분류',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flo.category',),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='질문')),
                ('answer', models.TextField(verbose_name='답변')),
                ('order', models.PositiveIntegerField(default=0, help_text='표시 순서 (낮을수록 먼저)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='flo.faqcategory', verbose_name='FAQ 카테고리')),
            ],
            options={
                'verbose_name': 'FAQ 항목',
                'verbose_name_plural': 'FAQ 항목 목록',
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('is_notice', models.BooleanField(default=False, verbose_name='공지사항')),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_post_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('categories', models.ManyToManyField(blank=True, related_name='posts', to='flo.category', verbose_name='카테고리(들)')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_study_post_posts', to=settings.AUTH_USER_MODEL, verbose_name='추천수')),
            ],
            options={
                'verbose_name': '학습 게시글',
                'verbose_name_plural': '학습 게시글 목록',
                'ordering': ['-is_notice', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='댓글 수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_post_comments', to=settings.AUTH_USER_MODEL, verbose_name='댓글 작성자')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='flo.post', verbose_name='원본글')),
            ],
            options={
                'verbose_name': '댓글',
                'verbose_name_plural': '댓글 목록',
                'ordering': ['created_at'],
            },
        ),
    ]
