# Generated by Django 4.2.21 on 2025-06-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="attached_file",
            field=models.FileField(blank=True, null=True, upload_to="attachments/"),
        ),
    ]
