# Generated by Django 4.2.21 on 2025-06-09 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("flo", "0002_post_attached_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="MajorCategory",
            fields=[],
            options={
                "verbose_name": "학습 게시판 대분류",
                "verbose_name_plural": "학습 게시판 대분류",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("flo.category",),
        ),
        migrations.CreateModel(
            name="MediumCategory",
            fields=[],
            options={
                "verbose_name": "학습 게시판 중분류",
                "verbose_name_plural": "학습 게시판 중분류",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("flo.category",),
        ),
        migrations.CreateModel(
            name="MinorCategory",
            fields=[],
            options={
                "verbose_name": "학습 게시판 소분류",
                "verbose_name_plural": "학습 게시판 소분류",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("flo.category",),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "전체 카테고리",
                "verbose_name_plural": "전체 카테고리 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="faqcategory",
            options={
                "verbose_name": "FAQ 카테고리",
                "verbose_name_plural": "FAQ 카테고리 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-is_notice", "-created_at"],
                "verbose_name": "학습 게시글",
                "verbose_name_plural": "학습 게시글 목록",
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="flo.category",
                verbose_name="상위 카테고리",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts",
                to="flo.category",
                verbose_name="카테고리(들)",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                blank=True,
                help_text="URL에 사용될 이름",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="닉네임",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pics/",
                        verbose_name="프로필 사진",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="post_attachments/%Y/%m/%d/", verbose_name="첨부파일"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 날짜"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_attachments",
                        to="flo.post",
                        verbose_name="게시글",
                    ),
                ),
            ],
            options={
                "verbose_name": "첨부파일",
                "verbose_name_plural": "첨부파일 목록",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
