# Generated by Django 5.2.1 on 2025-06-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='프로필 사진'),
        ),
    ]
