# Generated by Django 5.2.1 on 2025-06-02 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='post_attachments/%Y/%m/%d/', verbose_name='첨부파일')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 날짜')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_attachments', to='flo.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '첨부파일',
                'verbose_name_plural': '첨부파일 목록',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
