# Generated by Django 5.2 on 2025-06-03 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo", "0004_attachment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="문제 내용")),
                (
                    "explanation",
                    models.TextField(blank=True, null=True, verbose_name="해설"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="문제 순서"),
                ),
            ],
            options={
                "verbose_name": "시험 문제",
                "verbose_name_plural": "시험 문제 목록",
                "ordering": ["test_set", "order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="attached_file",
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="보기 내용")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="정답 여부"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="flo.question",
                        verbose_name="관련 문제",
                    ),
                ),
            ],
            options={
                "verbose_name": "객관식 보기",
                "verbose_name_plural": "객관식 보기 목록",
            },
        ),
        migrations.CreateModel(
            name="TestSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="생성된 시험", max_length=255, verbose_name="시험 제목"
                    ),
                ),
                (
                    "num_questions_requested",
                    models.PositiveIntegerField(
                        default=10, verbose_name="요청 문제 수"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_sets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "시험 세트",
                "verbose_name_plural": "시험 세트 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="question",
            name="test_set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="flo.testset",
                verbose_name="시험 세트",
            ),
        ),
        migrations.CreateModel(
            name="UploadedPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="pdfs/%Y/%m/%d/", verbose_name="PDF 파일"
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="원본 파일명"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="업로드 시간"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_pdfs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="업로더",
                    ),
                ),
            ],
            options={
                "verbose_name": "업로드된 PDF",
                "verbose_name_plural": "업로드된 PDF 목록",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="testset",
            name="source_pdf",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_tests",
                to="flo.uploadedpdf",
                verbose_name="원본 PDF",
            ),
        ),
        migrations.CreateModel(
            name="UserTestAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작 시간"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="완료 시간"
                    ),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="점수"),
                ),
                (
                    "test_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="flo.testset",
                        verbose_name="응시 시험",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="응시자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 시험 응시 기록",
                "verbose_name_plural": "사용자 시험 응시 기록 목록",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_answer",
                    models.TextField(
                        blank=True, null=True, verbose_name="입력한 답(주관식)"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="정답 여부"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flo.question",
                        verbose_name="질문",
                    ),
                ),
                (
                    "selected_choice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="flo.choice",
                        verbose_name="선택한 보기(객관식)",
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="flo.usertestattempt",
                        verbose_name="응시 기록",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 답변",
                "verbose_name_plural": "사용자 답변 목록",
                "unique_together": {("attempt", "question")},
            },
        ),
    ]
