# Generated by Django 5.2.1 on 2025-06-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0004_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='URL에 사용될 이름', unique=True),
        ),
    ]
