# Generated by Django 5.2.1 on 2025-06-12 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': '댓글 & 답글', 'verbose_name_plural': '댓글 & 답글 목록'},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='flo.comment', verbose_name='부모 댓글'),
        ),
    ]
