# Generated by Django 5.2 on 2025-06-04 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo", "0005_question_remove_post_attached_file_choice_testset_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="학습 목표 제목"),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("TEST_RETAKE", "Test 전체 다시 풀기"),
                            ("INCORRECT_ANSWERS_RETAKE", "오답만 다시 풀기"),
                        ],
                        max_length=30,
                        verbose_name="목표 유형",
                    ),
                ),
                (
                    "target_repetition_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="목표 반복 학습 횟수"
                    ),
                ),
                (
                    "current_repetition_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="현재 완료 횟수"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="학습 마감일")),
                (
                    "is_important",
                    models.BooleanField(
                        default=False,
                        verbose_name="중요 목표 여부 (최대 2개 선택 가능)",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="목표 달성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "target_attempt_for_incorrect_notes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals_for_incorrect_retake",
                        to="flo.usertestattempt",
                        verbose_name="오답노트 대상 응시기록",
                    ),
                ),
                (
                    "target_test_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals_for_test_retake",
                        to="flo.testset",
                        verbose_name="대상 TestSet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학습 목표",
                "verbose_name_plural": "학습 목표 목록",
                "ordering": ["-is_important", "due_date", "-created_at"],
            },
        ),
    ]
