# Generated by Django 5.2 on 2025-06-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flo", "0006_learninggoal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useranswer",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="useranswer",
            unique_together=set(),
        ),
    ]
