# Generated by Django 5.2 on 2025-06-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo", "0007_alter_useranswer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testset",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="중요 표시"),
        ),
    ]
