# Generated by Django 5.2 on 2025-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo", "0008_testset_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertestattempt",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="중요 오답노트"),
        ),
    ]
