# Generated by Django 5.2 on 2025-06-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo", "0009_usertestattempt_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertestattempt",
            name="duration_seconds",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="응시 시간(초)"
            ),
        ),
    ]
