name: Append Push Info to README

on:
  push:
    branches:
      - '**'  # 모든 브랜치

permissions:
  contents: write

jobs:
  update-readme-log:
    if: "!contains(github.event.head_commit.message, '[bot]')"  # 반복 방지
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions@github.com"

      - name: Append commit info to README.md
        run: |
          echo -e "\n### 📝 Commit Log\n" >> README.md   # escape 문자 해석 요청
          echo "**Author:** $(git log -1 --pretty=format:'%an')" >> README.md    # git log --> 문자열 출력
          echo "**Message:** $(git log -1 --pretty=format:'%s')" >> README.md
          echo "**Commit:** $(git log -1 --pretty=format:'%H')" >> README.md
          echo "**Date:** $(date '+%Y-%m-%d %H:%M:%S')" >> README.md      # +는 기본 출력 대신 내가 지정한 형식을 사용해 출력하라는 의미
          echo "" >> README.md

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update README with commit info [bot]" || echo "No changes"
          git push
