# Generated by Django 5.2.1 on 2025-06-12 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='문서 제목')),
                ('pdf_file', models.FileField(upload_to='uploaded_pdfs/', verbose_name='PDF 파일')),
                ('num_questions_requested', models.IntegerField(choices=[(10, '10문제'), (20, '20문제'), (25, '25문제')], default=10, verbose_name='요청 문항수')),
                ('question_type_requested', models.CharField(choices=[('객관식', '객관식(4지선다)'), ('단답형', '단답형')], default='객관식', max_length=20, verbose_name='요청 문제 유형')),
                ('subject_area', models.CharField(help_text='예: 수학, 정보처리기사, HTML, CSS 등', max_length=100, verbose_name='분야')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
                ('processing_status', models.CharField(choices=[('PENDING', '대기 중'), ('PROCESSING', '문제 생성 중'), ('COMPLETED', '생성 완료'), ('FAILED', '생성 실패')], default='PENDING', max_length=20, verbose_name='처리 상태')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '업로드된 PDF 문서',
                'verbose_name_plural': '업로드된 PDF 문서들',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('exam_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exam', to='flo_exam.examdocument', verbose_name='원본 PDF 문서')),
            ],
            options={
                'verbose_name': '생성된 시험 세트',
                'verbose_name_plural': '생성된 시험 세트들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='문제 번호')),
                ('question_text', models.TextField(verbose_name='문제 내용')),
                ('question_type', models.CharField(max_length=20, verbose_name='실제 문제 유형')),
                ('option1', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 1')),
                ('option2', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 2')),
                ('option3', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 3')),
                ('option4', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 4')),
                ('correct_answer', models.TextField(verbose_name='정답')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='해설')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flo_exam.generatedexam', verbose_name='소속 시험')),
            ],
            options={
                'verbose_name': '생성된 문제',
                'verbose_name_plural': '생성된 문제들',
                'ordering': ['exam', 'question_number'],
            },
        ),
        migrations.CreateModel(
            name='UserExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='점수')),
                ('generated_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flo_exam.generatedexam', verbose_name='응시한 시험')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='응시자')),
            ],
            options={
                'verbose_name': '사용자 시험 응시 세션',
                'verbose_name_plural': '사용자 시험 응시 세션들',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField(blank=True, null=True, verbose_name='제출한 답')),
                ('is_correct', models.BooleanField(null=True, verbose_name='정답 여부')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flo_exam.generatedquestion', verbose_name='해당 문제')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='flo_exam.userexamsession', verbose_name='응시 세션')),
            ],
            options={
                'verbose_name': '사용자 제출 답안',
                'verbose_name_plural': '사용자 제출 답안들',
                'ordering': ['session', 'question__question_number'],
            },
        ),
    ]
