# Generated by Django 5.2.1 on 2025-06-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('pdf_file', models.FileField(upload_to='uploaded_pdfs/', verbose_name='PDF 파일')),
                ('num_questions', models.IntegerField(choices=[(10, '10문제'), (20, '20문제'), (25, '25문제')], default=10, verbose_name='문항수')),
                ('question_type', models.CharField(choices=[('객관식', '객관식(4지선다)'), ('단답형', '단답형')], default='객관식', max_length=20, verbose_name='문제 유형')),
                ('subject_area', models.CharField(help_text='예: 수학, 정보처리기사 등', max_length=100, verbose_name='분야')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드 일시')),
            ],
            options={
                'verbose_name': '업로드된 시험 문서',
                'verbose_name_plural': '업로드된 시험 문서들',
            },
        ),
    ]
