# Generated by Django 4.2.21 on 2025-06-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo_exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examdocument",
            name="is_important",
            field=models.BooleanField(default=False, verbose_name="중요 표시"),
        ),
    ]
