# Generated by Django 5.2.1 on 2025-06-02 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo_exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examdocument',
            options={},
        ),
        migrations.AddField(
            model_name='examdocument',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('PROCESSING', '문제 생성 중'), ('COMPLETED', '생성 완료'), ('FAILED', '생성 실패')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='GeneratedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exam', to='flo_exam.examdocument')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(verbose_name='문제 번호')),
                ('question_text', models.TextField(verbose_name='문제 내용')),
                ('question_type', models.CharField(max_length=20, verbose_name='문제 유형')),
                ('option1', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지1')),
                ('option2', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지2')),
                ('option3', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지3')),
                ('option4', models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지4')),
                ('correct_answer', models.TextField(verbose_name='정답')),
                ('explanation', models.TextField(blank=True, null=True, verbose_name='해설')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flo_exam.generatedexam')),
            ],
        ),
    ]
