# Generated by Django 4.2.21 on 2025-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flo_exam", "0002_examdocument_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="userexamsession",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
