# Generated by Django 5.2.1 on 2025-06-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flo_exam', '0002_alter_examdocument_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examdocument',
            old_name='num_questions',
            new_name='num_questions_requested',
        ),
        migrations.RenameField(
            model_name='examdocument',
            old_name='question_type',
            new_name='question_type_requested',
        ),
    ]
