# Generated by Django 5.2.1 on 2025-06-04 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flo_exam', '0003_rename_num_questions_examdocument_num_questions_requested_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examdocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '업로드된 PDF 문서', 'verbose_name_plural': '업로드된 PDF 문서들'},
        ),
        migrations.AlterModelOptions(
            name='generatedexam',
            options={'ordering': ['-created_at'], 'verbose_name': '생성된 시험 세트', 'verbose_name_plural': '생성된 시험 세트들'},
        ),
        migrations.AlterModelOptions(
            name='generatedquestion',
            options={'ordering': ['exam', 'question_number'], 'verbose_name': '생성된 문제', 'verbose_name_plural': '생성된 문제들'},
        ),
        migrations.AddField(
            model_name='examdocument',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='examdocument',
            name='num_questions_requested',
            field=models.IntegerField(choices=[(10, '10문제'), (20, '20문제'), (25, '25문제')], default=10, verbose_name='요청 문항수'),
        ),
        migrations.AlterField(
            model_name='examdocument',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', '대기 중'), ('PROCESSING', '문제 생성 중'), ('COMPLETED', '생성 완료'), ('FAILED', '생성 실패')], default='PENDING', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='examdocument',
            name='question_type_requested',
            field=models.CharField(choices=[('객관식', '객관식(4지선다)'), ('단답형', '단답형')], default='객관식', max_length=20, verbose_name='요청 문제 유형'),
        ),
        migrations.AlterField(
            model_name='examdocument',
            name='subject_area',
            field=models.CharField(help_text='예: 수학, 정보처리기사, HTML, CSS 등', max_length=100, verbose_name='분야'),
        ),
        migrations.AlterField(
            model_name='examdocument',
            name='title',
            field=models.CharField(max_length=255, verbose_name='문서 제목'),
        ),
        migrations.AlterField(
            model_name='generatedexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 일시'),
        ),
        migrations.AlterField(
            model_name='generatedexam',
            name='exam_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated_exam', to='flo_exam.examdocument', verbose_name='원본 PDF 문서'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='flo_exam.generatedexam', verbose_name='소속 시험'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='option1',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 1'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='option2',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 2'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='option3',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 3'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='option4',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='선택지 4'),
        ),
        migrations.AlterField(
            model_name='generatedquestion',
            name='question_type',
            field=models.CharField(max_length=20, verbose_name='실제 문제 유형'),
        ),
        migrations.CreateModel(
            name='UserExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='점수')),
                ('generated_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flo_exam.generatedexam', verbose_name='응시한 시험')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='응시자')),
            ],
            options={
                'verbose_name': '사용자 시험 응시 세션',
                'verbose_name_plural': '사용자 시험 응시 세션들',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.TextField(blank=True, null=True, verbose_name='제출한 답')),
                ('is_correct', models.BooleanField(null=True, verbose_name='정답 여부')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flo_exam.generatedquestion', verbose_name='해당 문제')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='flo_exam.userexamsession', verbose_name='응시 세션')),
            ],
            options={
                'verbose_name': '사용자 제출 답안',
                'verbose_name_plural': '사용자 제출 답안들',
                'ordering': ['session', 'question__question_number'],
            },
        ),
    ]
